title: Emily Minkah-Premo # your name (or website title) here
logo: "/images/profile-img.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pharmacist|Data Engineer|Entrepreneur 
  <br><br>
  Result-oriented data engineer with with great communication skills and a background in Pharmacy. I am a highly analytical person with strong apt for learning and collaborative skills, detail oriented and possess the ability to adapt quickly in the fast-paced tech sapce. Looking to apply my knowledge in data engineering extensively to solve problems pertaining to data infrastructure.
  <br><br>
  <a href="https://www.linkedin.com/in/emily-minkah-premo-7489bb101/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
